# Generated by Django 4.0.3 on 2022-03-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('URLSlug', models.SlugField(max_length=150, unique=True)),
                ('summary', models.CharField(max_length=350)),
                ('body', models.TextField()),
                ('published', models.BooleanField(default=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
